[package]
edition = "2021"
name = "ecdsa"
version = "0.1.0"

[dependencies]
bigint = "4.4.3"
hex = "0.4.3"
hex-literal = "0.4.1"
num = "0.4.3"
num-bigint = {version = "0.4.0", features = ["rand"]}
rand = "0.8.5"
sha2 = "0.10.8"
