[package]
edition = "2021"
name = "ecdsa"
version = "0.1.0"

[dependencies]
bigint = "4.4.3"
crypto-bigint = "=0.6.0-pre.12"
modular_math = "=0.1.1"
modulo-n-tools = "0.2.0"
num = "0.4.3"
num-bigint = {version = "0.4.0", features = ["rand"]}
num-traits = "0.2.19"
rand = "0.8.5"
sha2 = "0.10.8"
